test:error_functions.c get_num.c  tlpi_hdr.h \
	error_functions.h get_num.h get_num.h ename.c
	gcc main.c error_functions.c get_num.c tlpi_hdr.h \
	error_functions.h get_num.h get_num.h ename.c -o test
clean:
	rm test
		